# List of quick example requests for all controllers in this project.

# "REST Client" VS Code extension can be used to send requests on .http files
# Click "Send Request" button to send request to highlighted URL
# If "Send Request" button does not appear on top of request URLs; 
# highlight desired request line and press f1 -> select "Rest Client: Send Request"

<!-- # Request Structure:

<Http Protocol> <Url>
<Request Header>

<Request Body as JSON>
-->

### [POST] Register
# Send registration info as json in request body
# Returns AccessToken and RefreshToken
# Sends Corfirmation Mail to user mail address with user's email_token
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "email": "test1@testmail.com",
    "password": "testpassword"
}

### [POST] Login
# Send login info as json in body
# Returns AccessToken and RefreshToken
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "test1@testmail.com",
    "password": "testpassword"
}

### [POST] Generate Access Token
# Generate new access token using the refresh token in body
# Returns AccessToken
POST http://localhost:3000/api/auth/generateAccessToken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1IiwiZW1haWwiOiJ0ZXN0MUB0ZXN0bWFpbC5jb20iLCJpYXQiOjE3NDMyNTA5NzcsImV4cCI6MTc0Mzg1NTc3N30.SSmXxhlYcVjoH-LIicQiY87qCCgwsam5KayDzcyqwGc"
}

### [GET] Check Access Token
# Check if token is verified via veriftToken middleware that reads accessToken from "Authorization" request header 
# Use AccessToken created from generateAccessToken controller for Bearer token
GET http://localhost:3000/api/auth/checkAccessToken
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1IiwiZW1haWwiOiJ0ZXN0MUB0ZXN0bWFpbC5jb20iLCJpYXQiOjE3NDMyNTA5OTIsImV4cCI6MTc0MzI1MTg5Mn0.sEMreSiVGIsVxoErd4pMxmvt980caaj5UANoKioh8ME

### [POST] Confirm Email Token
# Get email token from confirmation mail 
# Use Bearer <access_token> in request headers
# Use <emailToken> in request parameters
# Email example: "Click the link to confirm your email: http://localhost:9000/confirm-email/<emailToken>"
POST http://localhost:3000/api/auth/confirmEmailToken
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1IiwiZW1haWwiOiJ0ZXN0MUB0ZXN0bWFpbC5jb20iLCJpYXQiOjE3NDMyNTA5OTIsImV4cCI6MTc0MzI1MTg5Mn0.sEMreSiVGIsVxoErd4pMxmvt980caaj5UANoKioh8ME

{
    "emailToken": "de2157ac-4cb7-48ff-b7db-148c400a8d3e"
}

### [POST] Reset Password 
# Sends password reset mail with user's passwordResetToken
# Since user requests password reset, not logged in, does not require Authorization token (AccessToken)
POST http://localhost:3000/api/auth/resetPassword
content-type: application/json

{
    "email": "test1@testmail.com",
    "provisionalPassword": "testtest2"
}

### [POST] Reset Password Confirm
# Click the link to confirm your password reset: http://localhost:9000/confirm-password/<passwordResetToken>
POST http://localhost:3000/api/auth/resetPasswordConfirm
content-type: application/json

{
    "email": "test1@testmail.com",
    "passwordResetToken": "86919ad0-32b1-40e1-a71d-b3547f96c131"
}

### [POST] Change Email 
POST http://localhost:3000/api/auth/changeEmail
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0bWFpbC5jb20iLCJpYXQiOjE3NDM5NTg0MzIsImV4cCI6MTc0Mzk1OTMzMn0.piipKsYKJ_crBTcC1QacEiAZpEzidEA2ovfvBCpagK4

{
    "provisionalEmail": "test2@testmail.com"
}

### [POST] Change Email Confirm 
# Click the link to confirm your new email change: http://localhost:9000/confirm-email-change/<changeEmailToken>
POST http://localhost:3000/api/auth/changeEmailConfirm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0bWFpbC5jb20iLCJpYXQiOjE3NDM5NTg0MzIsImV4cCI6MTc0Mzk1OTMzMn0.piipKsYKJ_crBTcC1QacEiAZpEzidEA2ovfvBCpagK4

{
    "changeEmailToken": "0832e2b0-11b6-4aa7-9ef2-0c4df9c12c7f"
}


### Test Token Routes

# [POST] Generate Test Token
POST http://localhost:3001/api/test/generateTestToken

### [GET] Check Test Token (without token)
# Try without token, will get error:
GET http://localhost:3001/api/test/checkTestToken

### [GET] Check Test Toke (with token)
# Send req with token in headers (get token with generateToken controller)
GET http://localhost:3001/api/test/checkTestToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MzU3NDY2NzMsImV4cCI6MTczNTc0NzU3M30.QwATy_M63zhYHmFzmv3_31sQd1ZlZII4jtrLcwfQy_A
